# Why is there a key error?

d = {"Name": "John", "Surname": "Smith"}
print(d["Surname"])

# There was a key error because "Smith" is a value and not a key
